
<?php
//this file is generated by enact upon installation
return Array(
'AES_KEY256' => '50c8d17bd94e8d74bd14cdb12e37e641',
'SHA512_SALT_LEAD' => '1ba3808c36d6',
'SHA512_SALT_TAIL' => 'e1973246bb42',
'ENACT_INSTALLED' => '1',

);
